spring.application.name=spring-7-auth-server
server.port=9000

# ENABLE COLOR ON TERMINAL ENTRIES
spring.output.ansi.enabled=ALWAYS

# security logging
logging.level.org.springframework.security=trace
